---
title: "On_modifie__après"
author: "Adrian Et Théo"
date: "2024-10-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Calcul des KPI pertinents (répartition des étiquettes DPE, etc.)
kpi_dpe <- data_dpe %>%
  group_by(Etiquette_DPE) %>%
  summarise(Count = n()) %>%
  arrange(desc(Count))

kpi_dpe %>%
  kable() %>%
  kable_styling(bootstrap_options = "striped", full_width = FALSE)

```

```{r}
# Exemple d'analyse bivariée
ggplot(data_dpe, aes(x = Année_construction, fill = Etiquette_DPE)) +
  geom_bar() +
  labs(title = "Répartition des étiquettes DPE par année de construction",
       x = "Année de construction",
       y = "Nombre de logements")

```

```{r}
# Graphique de la répartition des étiquettes DPE
ggplot(kpi_dpe, aes(x = Etiquette_DPE, y = Count, fill = Etiquette_DPE)) +
  geom_bar(stat = "identity") +
  labs(title = "Répartition des étiquettes DPE", x = "Étiquette DPE", y = "Nombre de logements") +
  theme_minimal()
```


```{r}
# Graphique de répartition des types de logements
logement_type_data <- data_dpe %>%
  group_by(Type_bâtiment) %>%
  summarise(Count = n())

ggplot(logement_type_data, aes(x = Type_bâtiment, y = Count, fill = Type_bâtiment)) +
  geom_bar(stat = "identity") +
  labs(title = "Répartition des types de logements", x = "Type de logement", y = "Nombre de logements") +
  theme_minimal()

```

```{r}
# Graphique de la répartition des étiquettes DPE par année de construction
ggplot(data_dpe, aes(x = Année_construction, fill = Etiquette_DPE)) +
  geom_histogram(binwidth = 5, position = "fill") +
  labs(title = "Répartition des étiquettes DPE par année de construction",
       x = "Année de construction",
       y = "Proportion de logements") +
  theme_minimal()

```

```{r}
# Boxplot des étiquettes DPE par année de construction
ggplot(data_dpe, aes(x = as.factor(Année_construction), y = Etiquette_DPE, fill = Etiquette_DPE)) +
  geom_boxplot() +
  labs(title = "Performance énergétique (DPE) par année de construction", 
       x = "Année de construction", 
       y = "Étiquette DPE") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

```
```{r}

# Calcul de l'âge des logements
data_dpe$Age_logement <- 2024 - data_dpe$Année_construction

# Histogramme de l'âge des logements
ggplot(data_dpe, aes(x = Age_logement)) +
  geom_histogram(binwidth = 5, fill = "blue", color = "white") +
  labs(title = "Distribution de l'âge des logements", 
       x = "Âge du logement (en années)", 
       y = "Nombre de logements") +
  theme_minimal()

```


